version: '3.8'

services:
  reverseproxy:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./.docker/toggleit.pem:/etc/ssl/certs/toggleit.crt
      - ./.docker/toggleit.key.pem:/etc/ssl/private/toggleit.key
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      API_GLOBAL_PREFIX: ${NEST_API_GLOBAL_PREFIX}
      API_URL: ${LOCAL_IPV4_ADDR}:3000
      APP_URL: ${LOCAL_IPV4_ADDR}:3002
    ports:
      - 80:80
      - 443:443

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
